# SPDX-License-Identifier: MIT-0
---
# tasks file for mariadb

- name: Mariadb-server installation
  apt:
    name: "mariadb-server,python3-mysqldb"
    state: "present"
    update_cache: true

- name: Start mariadb service
  service:
    name: "mariadb"
    state: "started"
    enabled: true

- name: Change 50-server.cnf
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address\s*=\s*127\.0\.0\.1'
    line: 'bind-address = 0.0.0.0'
    state: present

- name: Restart mariadb
  service:
    name: "mariadb"
    state: "restarted"
