# MariaDB config task
---
- name: "Mediawiki database"
  community.mysql.mysql_db:
    name: "{{ commun_mediawiki_db_name }}"
    state: present

- name: "Mediawiki database user and privileges"
  community.mysql.mysql_user:
    name: "{{ commun_mediawiki_db_user }}"
    password: "{{ commun_mediawiki_db_password }}"
    priv: "{{ commun_mediawiki_db_name }}.*:ALL"
    host: "%"
    state: present
